### ISSUE TITLE
Decode fields according to table values in MSA specs

### ISSUE THREAD

**Issue by insekt** [ocpnetworking-wip/oom#15]
It would be nice to have an option to decode these fields - TRANSCEIVER, BR_NOMINAL, IDENTIFIER, CONNECTOR, ENCODING, OPTIONS, DATE_CODE as they described in MSA tables.
I think the main question what is the right method how to do it. It definitely should be optional.

**Comment by donboll** [comment]
There is a mechanism in OOM to add additional keys.  See oom/oom/addonsample.py

This file explains the mechanism and provides an example for adding keys.  Note that the existing keyfiles are not modified.  Any number of additional key files can be added independently, all of them will be merged into one working set of keys at run time.

If an interesting set of keys is developed, I am likely to be willing to add the keyfile or merge it into one of the existing files.  Let me know if you would like to contribute.

Don
